### ISSUE TITLE
Gridview not working.

### ISSUE THREAD

**Issue by Sneethe** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#12]
Is the 
> DPad Up/Down: Access SwitchView UI menu

Enabled for v2.2?
For me the buttons have no effect. Thus gridview is inaccessible.

**Comment by BlackSheepBoy69** [comment]
SwitchView UI menu is only for SwitchView (view number 5) not Grid View (view number 6). In Grid View, up and down should only move you up and down, right?

Or if what you're saying is that SwitchView or Grid View aren't showing up... did you enable them in settings? Press Start > "Allow View 5/6: ON"

**Comment by Sneethe** [comment]
>"Allow View #5/#6: ON" 

Bingo. Thanks a ton. I think I ended up testing each and every option. And assumed that the "Allow View", just meant that more titles would be shown on the horizontal line (Allow View (ing) +5/6). It sounds pretty stupid now that I type this....
