### ISSUE TITLE
Is there a community discord? 

### ISSUE THREAD

**Issue by ste2425** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#14]
I understand these kind of questions are not normally good GitHub etiquette (i do know better honest!) However not too sure where else to ask.

Is there a community Discord or anything similar around this fork? 

I ask because i see you are working on V3 and it would be great to see any progress updates on that endeavour. Also it may be good for the maintainers of this project to not work in a potential vacuum. I suspect it may be good for moral and motivation for the maintainers (even though i understand this fork was sparked as a personal project to feel personal requirements)

**Comment by BlackSheepBoy69** [comment]
A good way to watch when there will be an update though might be to go to the main page:
[https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom](https://github.com/BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom)
...and click 'watch' at the top right of the screen. Then it will email you if there is an update. Even if there is the V3.0 update, it will help you in case there is anything after that, such as a V3.0.1 hotfix
