### ISSUE TITLE
Nopspemudrm support?

### ISSUE THREAD

**Issue by Youngei402tw** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#17]
I am wondering if this launcher can support launching all the psp emu games without adrenaline? Since nopspemudrm is here already. Wouldn't it be great if we don't need adrenaline to launch psp games from the launcher?

**Comment by BlackSheepBoy69** [comment]
This seems very promising, I will be looking into this!

**Comment by BlackSheepBoy69** [comment]
I tried it out. It's much cleaner to populate and launch games this way. This is how the Vita was meant to play them and it's the same way they come out of the store like.

...but Adrenaline just has a lot more features that make it worth spending the short amount of time setting up. It is apparent just how much better Adrenaline is the second you press the PS button, it brings up all sorts of configuration stuff. With Adrenaline Bubble Manager, you can set up whether you'd like the PS button to bring up this little menu or whether it should bring you right to the LiveArea as it would with NoPspEmuDrm. Also I think you need Adrenaline for GEPatch (currently the only solution for full-resolution on some PSP games)

**Comment by Youngei402tw** [comment]
@BlackSheepBoy69 Some people do argue that nopspemudrm has a better performance over the adrenaline method.

**Comment by BlackSheepBoy69** [comment]
Not completely sure the benefits except that it's cleaner. If there are some games that this works for that Adrenaline doesn't work at all on, I may look into it more. People online say the performance boost is tiny/unnoticeable
