### ISSUE TITLE
Allow using retroarch for PS1 games

### ISSUE THREAD

**Issue by mmayfield** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#5]
Would love to be able to select using retroarch for PS1 games. Retroarch works for many games Adrenaline doesn't and you get retro-achievements.

**Comment by BlackSheepBoy69** [comment]
There's only like 5 games the latest Adrenaline can't play that Retroflow can, but either way this launcher is compatible with the Retroarch bubbles. There are several bubble builders for Retroarch: [W00lfwang](https://www.reddit.com/user/W00lfwang/)'s (I recommend it), [DRok17](https://github.com/DRok17/RetroBuilder/commits?author=DRok17)'s, and [AntHJ](https://github.com/AntHJ/Retroarch-Bubble-Builder/commits?author=AntHJ)'s (not recommended). set core to the PCSX Rearmed core, and in HexLauncher Custom, override it from homebrew (where it will be by default) to PS1. If you set the ID to the same as the PS1 ID, it'll be able to download covers just fine while in the PS1 category.

**Comment by mmayfield** [comment]
In my experience it's A LOT more than 5, but I didn't make a list or anything. Back before I got a Vita, my PSP was on 6.61 and I had a lot of games that only ran using popsloader versions and popsloader isn't supported in Adrenaline. I already have way more bubbles than the interface really supports (icons stop loading after you hit a certain number of bubbles) so I'm not trying to make more. But if it's something you don't want to integrate I guess that is that. Thanks anyway

**Comment by BlackSheepBoy69** [comment]
I would be interested to know which ones can't run in Adrenaline but can run in Retroflow. What compression level do you usually use in PSX2PSP? If you set it wrong, a lot of games will crash.

**Comment by BlackSheepBoy69** [comment]
A list of titles would hugely help since I can test it myself since I thought like 99% of games did work. I have a huge PS1 collection so more than likely I have some of these games you'll list (though I haven't actually tested all the PS1 games on Vita, but I have on the actual PS1)

**Comment by mmayfield** [comment]
Donald Duck Going Quackers, Duke Nukem Land of Babes, Driver are a few of them. I didn't have a lot time to test. To me retro achievements are a bigger draw for retroarch/pcsx over adrenaline for PS1 games. I can always go through the retroarch gui, it'd just be nice to have them native in the launcher like the other retroarch cores are in retroflow. There was a feature request for it by someone in retroflow a while back so I know I'm not the only one.

**Comment by BlackSheepBoy69** [comment]
I could've sworn I played Driver, I'll test it out in a second. I can immediately say, though, that I could make a fork of Retroflow with PS1 Retroarch support, that would be super easy and take like an hour max. What is the exact full name of the PS1 Retroarch core file? example: gambatte_libretro.self

**Comment by mmayfield** [comment]
Driver 2 works, Driver 1 doesn't for me at least not the version I had. PAL/NTSC and different game versions can affect whether it works or not. I didn't know how close you were to integrating the retroflow features, I thought you were really close. A retroflow fork or getting the changes in retroflow would be great for now. PS1 in retroarch on Vita works great for me. Ill post the full core path after I get off work.

You can see here someone else asked for this in retroflow. https://github.com/jimbob4000/RetroFlow-Launcher/issues/63

**Comment by mmayfield** [comment]
pcsx_rearmed_libretro.self

**Comment by BlackSheepBoy69** [comment]
>I thought you were really close
As I said it's been done but it just imports cache from Retroflow. The hard part of Retroflow is making cache, the easy part is launching. Setting up a fork of Retroflow with Retroarch PS1 would be a lot easier since the code is basicly already there (ex: for Sega CD). I'll check it all out this weekend and get back to you. The question is how cover downloads would work for cue/bin when it's used to just checking the folder name... I'll let you know how it goes.

**Comment by jimbob4000** [comment]
It's a bit messier to add than other retro systems as overrides need to apply. There's quite a few extensions to support, including eboot.pbp which needs a database lookup. https://docs.libretro.com/library/pcsx_rearmed/

Additional covers and snaps will also need to be added. 

I'll have a look at adding it to retroflow

**Comment by BlackSheepBoy69** [comment]
Hello Jimbob4000!!! Not sure what you mean about eboot.pbp, but I think the .cue files can be scanned in binary to extract the ID so that you can continue to use the original cover archive.

**Comment by jimbob4000** [comment]
Hi

eboot.pbp files are normally stored in folders using the game's title ID (SLUS...). 
So these parent folder names can be used to for cover matching and database lookup to get the name of the game.

Getting the bin name from the cue file and then scanning the bin in binary sounds quite slow.
I'm just going to treat it like the other retro systems. Name the cue files like: 'Game name (USA).cue'

**Comment by BlackSheepBoy69** [comment]
Dang that's fast reply. Anyway I was editting my comment to say that I just checked some .cue's and actually the ID is not there, just a file name. You can check it out if you drag and drop the .cue into notepad. But on the good side, every cue/bin file I have somehow came preloaded with a Retroflow-recognizeable name ('Game name (USA).cue'). Normally psx.db is used in retroflow to put an ID in and get a name out, can it be used the other way around?

**Comment by BlackSheepBoy69** [comment]
I imagine putting cue/bin recognition AND eboot recognition in at the same time would be a mess and especially cue/bins would make it a mess for applying overrides. Maybe put an option in settings saying "PSX file type: EBOOT.PBP (default) / cue&bin (can't use overrides)" and then possibly disable overrides for cue&bin psx games?

**Comment by jimbob4000** [comment]
You're right, the overrides are problematic I may disable it for retroarch ps1 games.

The database names won't match the names people are using for games, usa would be shown as ' (NTSC-U)' instead of 'USA', there would be a lot of missing covers if i try to rework the data.

I'm going to take the shortest route to getting this added, not looking to spend much time on it.

**Comment by BlackSheepBoy69** [comment]
I haven't checked psx.db but I have checked psx.lua: There's entries for each nation (usa/ntsu-u/etc) so if during cover download you punch in the whole name, NOT cutting off "(usa)" then it can return the actual correct ID and you could use the original cover archive. Not sure which way would be the "shortest route" if it's this or to give it its own cover archive or what. The easiest way would be no covers but people would complain

**Comment by BlackSheepBoy69** [comment]
There was one more thing. If you let people use cue/bin, I'm 99% sure RetroArch needs a PS1 bios for pcsx rearmed to work properly, otherwise compatability is trash. You may want to put a warning or a little tidbit in the about section or etc.

**Comment by jimbob4000** [comment]
I'll go with adding more covers and snaps instead of messing with databases.
For bios etc. its's down to the user to setup retroarch properly, most systems need bios.

**Comment by BlackSheepBoy69** [comment]
Oh yeah I forgot about that. Anyway thank you for adding this feature if you do!!

**Comment by mmayfield** [comment]
> You're right, the overrides are problematic I may disable it for retroarch ps1 games.
> 
> The database names won't match the names people are using for games, usa would be shown as ' (NTSC-U)' instead of 'USA', there would be a lot of missing covers if i try to rework the data.
> 
> I'm going to take the shortest route to getting this added, not looking to spend much time on it.

I'm not sure if you're looking at a global or per game toggle for adrenaline vs retroarch. I would be more than happy with a global toggle. If you select retroarch for ps1 in settings it only scans the retroarch folder and if you select Adrenaline it only scans Adrenaline. I guess a per game would provide more compatibility though. 

Out of curiosity, would it not be easier to just take advantage of retroarch playlists and just import those instead of scanning?

**Comment by jimbob4000** [comment]
I'm working on the basis that games can in in the adrenaline folder and also a rom folder. This was you can have the best of both as the same time rather than using a global toggle. 

I thought about importing playlists in the beginning, but wanted to keep the setup time as low as possible to keep things simple for people, ie not having to choose cores etc.

**Comment by jimbob4000** [comment]
@mmayfield RetroArch PS1 support has been added to this pre-release if you want to give it a go:
https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/4.0.2

**Comment by BlackSheepBoy69** [comment]
Bruh that fast? Nice!!!

**Comment by mmayfield** [comment]
> @mmayfield RetroArch PS1 support has been added to this pre-release if you want to give it a go: https://github.com/jimbob4000/RetroFlow-Launcher/releases/tag/4.0.2

That's awesome. I'll give a try in a few hours, got some household duties to take care of.

**Comment by mmayfield** [comment]
I was able to launch DN Land of Babes w/out issue. It didn't find a cover but I probably don't have it named right yet.

**Comment by jimbob4000** [comment]
> I was able to launch DN Land of Babes w/out issue. It didn't find a cover but I probably don't have it named right yet.

Cool, I'll probably share the release tomorrow or a little later.  

Let me know if you get any errors. 
You can have a look at my cover repo or retroarch's repo for naming. 

https://github.com/jimbob4000/hexflow-covers/tree/main/Covers/PS1

https://github.com/libretro-thumbnails/Sony_-_PlayStation/tree/master/Named_Boxarts

**Comment by mmayfield** [comment]
I got all my covers downloaded. I didn't have cue's for some (just bins) so I took a simple one and used it as a template to make the others. I had to rename some basically just adding " (USA)" at the end. Now it's all nice and clean. All my games work and they all have covers. Awesome work!

**Comment by BlackSheepBoy69** [comment]
Added RetroArch PS1 in the new RetroFlow+Grid View update V2.0!!!
