### ISSUE TITLE
Add Category for Vita system apps

### ISSUE THREAD

**Issue by mmayfield** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#6]
Would be great to have a category for system apps like trophies, vita settings etc. That way one can have the launcher run at startup and not have to go back to the Vita UI for anything.

**Comment by BlackSheepBoy69** [comment]
System apps have a special property where you can open them while you have another app open. I added system apps in SwitchView (enable view 5 via the start menu) thinking that I would use it a lot but I honestly, much more often I find myself just going to the actual Vita LiveArea and opening them there so I don't have to close my game. Many of the system apps are included in SwitchView but trophies are not. I have no idea how to do it but I was thinking possibly maybe one day to have it where you can view a game's manual via the triangle menu (functionality should be: 1: go in triangle menu, 2: click "view game manual" 3: it will open the app and open it's manual but still keep the HexLauncher Custom app running). This gives me the idea to do something similar where you can click "view this game's trophies" via triangle menu. Then you could hit circle to view all trophies. I'll add this all to my to-do list now.

**Comment by mmayfield** [comment]
"System apps have a special property where you can open them while you have another app open but HexLauncher Custom itself doesn't have this property." I had wondered about this some and it is problematic. Having to close Hexflow would somewhat defeat the purpose, but wouldn't it leave the launcher window open? So when you are done in the system app you just over to the HexFlow launcher tab and relaunch without going back through the live area bubbles? I have well over 100 bubbles and after the live area processes so many the icons stop working, I'd like to basically make the live area unnecessary. As of now (currently using Retroflow) I only need it for the settings and trophies apps.

 Being able to lock apps to home screen tabs would work but that wouldn't be a HexFlow/RetroFlow thing.

**Comment by BlackSheepBoy69** [comment]
I really am considering adding just a "system apps" category though. I might have to do more research into it/check the code for vitalauncher which has it

**Comment by BlackSheepBoy69** [comment]
This is getting added in the next few days in version 2.2, sorry it took so long!!!!!
