### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by hesh-monster** [BlackSheepBoy69/HexFlow-Launcher-Unofficial-Custom#7]
Would like to see the ability to scan a single category when adding new titles rather than having to scan everything.

**Comment by BlackSheepBoy69** [comment]
Next version will have rolling cache so there won't ever have to be another startup scan, it will just ask the system for listdirectory data every time. It's just this thing is a b*tch to bugtest because too many features are being added at once like RetroFlow and Grid view, and something really bad happened to the other person that was working on this app with me (other than RetroFlow team) so it's taking me a little bit longer sorry

**Comment by BlackSheepBoy69** [comment]
@hesh-monster While I'm still working out GPU crashes on the RetroFlow integration (specifically, for making overrides work on Retro entries) would you be interested if I went back and just made a HexFlow Launcher Unofficial Custom v1.1 with just rolling cache added?

**Comment by BlackSheepBoy69** [comment]
👍👍 I'll put it up tomorrow evening and make a cool release image for it even though there will probably be another update within a few days/etc afterwards to add RetroFlow/etc. Going to bed tonight. You'll have to see it rolling cache is really cool

**Comment by hesh-monster** [comment]
Ik forward to it, excellent work👏🏻

**Comment by BlackSheepBoy69** [comment]
Should be good to go 👍👍👍

Check it out and see if everything's good if you get a sec. It has many good features

**Comment by hesh-monster** [comment]
Cache updates are nearly instant now, absolutely fantastic👏🏻 I appreciate the intermediate release and I'm really looking forward to the next full compile with retroflow reintegrated.

**Comment by BlackSheepBoy69** [comment]
Glad you like it, the RetroFlow feature combined with rolling cache is really great but it causes hard-crashes on the Vita (when doing overrides and sometimes while downloading covers) that the LUA anti-crasher can't handle and every time it takes a few minutes for the Vita to get itself back to normal. I thought  it would be an easy fix but I'm still looking into it.

**Comment by BlackSheepBoy69** [comment]
Some people had issues with V1.1, this new version V1.2 should fix any issues if you had any while I go work out RetroFlow integration
